[package]
name = "synod"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[lints]
workspace = true

[lib]
name = "synod"
path = "src/lib.rs"

[dependencies]
ral-core   = { path = "../core", features = ["grep", "coreutils"] }
exarch     = { path = "../exarch" }
vm-manager = { path = "../vm-manager" }
serde      = { workspace = true }
serde_json = { workspace = true }
blake3     = "1"
tokio      = { version = "1", features = ["rt"] }

[dev-dependencies]
ctor = "1"
