[package]
name = "ral-initramfs"
version = "0.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[lints]
workspace = true

[dependencies]
ral-daemon = { path = "../ral-daemon" }

[target.'cfg(target_os = "linux")'.dependencies]
rustix = { workspace = true, features = ["process", "mount", "fs", "system", "stdio"] }
