[package]
name = "ral-initramfs"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ral-daemon = { path = "../ral-daemon" }

[target.'cfg(target_os = "linux")'.dependencies]
rustix = { workspace = true, features = ["process", "mount", "fs", "system", "stdio"] }
