#!/bin/sh
set -e

RAL_SH=/usr/bin/ral-sh

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if [ -f /etc/shells ]; then
        grep -vxF "$RAL_SH" /etc/shells > /etc/shells.tmp || true
        mv /etc/shells.tmp /etc/shells
    fi
fi
