# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: lambdabetaeta.ral
PackageVersion: 0.2.0
InstallerType: wix
Commands:
  - ral
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/lambdabetaeta/ral/releases/download/v0.2.0/ral-windows.msi
    InstallerSha256: 0000000000000000000000000000000000000000000000000000000000000000
ManifestType: installer
ManifestVersion: 1.10.0
