use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::PathBuf;

fn extract_prelude_exports(src: &str) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    for line in src.lines() {
        if let Some(rest) = line.strip_prefix("let ") {
            let name = rest
                .split(|c: char| c.is_whitespace() || c == '=')
                .next()
                .unwrap_or("")
                .trim();
            if !name.is_empty() {
                out.insert(name.to_string());
            }
        }
    }
    out
}

fn render_manifest(names: &BTreeSet<String>) -> String {
    let mut s = String::new();
    s.push_str("// @generated by build.rs from src/prelude.ral\n");
    s.push_str("pub const PRELUDE_EXPORTS: &[&str] = &[\n");
    for n in names {
        s.push_str("    ");
        s.push('"');
        s.push_str(n);
        s.push_str("\",\n");
    }
    s.push_str("];\n");
    s
}

fn main() {
    println!("cargo:rerun-if-changed=src/prelude.ral");

    let src = fs::read_to_string("src/prelude.ral").expect("failed to read src/prelude.ral");
    let names = extract_prelude_exports(&src);
    let manifest = render_manifest(&names);

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    fs::write(out_dir.join("prelude_manifest.rs"), manifest)
        .expect("failed to write prelude manifest");
}
