use std::collections::BTreeMap;
use std::env;
use std::fmt::Write;
use std::fs;
use std::path::PathBuf;

/// One line of `prelude.ral`, as the scraper reads it.  A top-level `let` and
/// its `##` block both sit at column 0, so an indented line is `Other` — and
/// so is a blank one, which discards a pending doc.
enum Line<'a> {
    /// A bare `##`, closing the summary paragraph.
    Close,
    Doc(&'a str),
    Let(&'a str),
    Other,
}

fn read(line: &str) -> Line<'_> {
    if line.trim_end() == "##" {
        Line::Close
    } else if let Some(doc) = line.strip_prefix("## ") {
        Line::Doc(doc.trim_end())
    } else if let Some(rest) = line.strip_prefix("let ") {
        Line::Let(
            rest.split(|c: char| c.is_whitespace() || c == '=')
                .next()
                .unwrap_or("")
                .trim(),
        )
    } else {
        Line::Other
    }
}

/// The paragraph accumulating above the next `let`, and whether a bare `##`
/// has closed it.
#[derive(Default)]
struct Pending {
    summary: Option<String>,
    closed: bool,
}

/// Every top-level `let` in `src`, each with the summary above it: the lead
/// paragraph of its `##` block, doc lines joined with spaces.
fn exports(src: &str) -> impl Iterator<Item = (&str, Option<String>)> {
    src.lines()
        .scan(Pending::default(), |pending, line| {
            Some(match read(line) {
                Line::Close => {
                    pending.closed |= pending.summary.is_some();
                    None
                }
                Line::Doc(doc) if !pending.closed => {
                    match &mut pending.summary {
                        Some(summary) => {
                            summary.push(' ');
                            summary.push_str(doc);
                        }
                        empty => *empty = Some(doc.to_string()),
                    }
                    None
                }
                Line::Doc(_) => None,
                Line::Let(name) => {
                    pending.closed = false;
                    Some((name, pending.summary.take()))
                }
                Line::Other => {
                    *pending = Pending::default();
                    None
                }
            })
        })
        .flatten()
        .filter(|(name, _)| !name.is_empty())
}

/// `{:?}` on a `str` is exactly a Rust string literal, escapes and all.
fn render(entries: &BTreeMap<&str, Option<String>>) -> String {
    let names = entries.keys().fold(String::new(), |mut rows, name| {
        let _ = writeln!(rows, "    {name:?},");
        rows
    });
    let docs = entries
        .iter()
        .filter_map(|(name, doc)| doc.as_ref().map(|doc| (name, doc)))
        .fold(String::new(), |mut rows, (name, doc)| {
            let _ = writeln!(rows, "    ({name:?}, {doc:?}),");
            rows
        });
    format!(
        "// @generated by build.rs from src/prelude.ral\n\
         pub const PRELUDE_EXPORTS: &[&str] = &[\n{names}];\n\
         pub const PRELUDE_DOCS: &[(&str, &str)] = &[\n{docs}];\n"
    )
}

#[allow(
    clippy::disallowed_methods,
    reason = "[io-door:silent:prelude-bake-build] Build-time read of src/prelude.ral to bake the prelude manifest into the crate. Build scaffolding, not turn-time model data I/O — raises no surface card."
)]
fn main() {
    println!("cargo:rerun-if-changed=src/prelude.ral");

    let src = fs::read_to_string("src/prelude.ral").expect("failed to read src/prelude.ral");
    let manifest = render(&exports(&src).collect());

    // Build script — no access to crate::path helpers, OUT_DIR is
    // injected by cargo as already-resolved.
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    fs::write(out_dir.join("prelude_manifest.rs"), manifest)
        .expect("failed to write prelude manifest");
}
