//! Command-line surface and the system-prompt loader.
//!
//! Parses argv via clap and resolves `-s/--system FILE...` into the
//! string handed to the provider.  The default prompt is the markdown
//! pair under `exarch/data/`, baked at compile time.

use crate::api::ProviderKind;
use clap::Parser;

/// Default system prompt — the user-overridable narrative half, baked
/// from the markdown fragments in `data/`.  `--system FILE...` replaces
/// this; the prelude reference below is always appended regardless.
const NARRATIVE: &str = concat!(
    include_str!("../data/system.md"),
    "\n",
    include_str!("../data/ral.md"),
);

/// Authoritative `name : type — purpose` prelude listing generated by
/// `build.rs` from the same schemes the exarch runs with.  Always
/// appended to whatever narrative the user gave so a custom prompt
/// can't accidentally lie about which builtins exist.
const PRELUDE_REF: &str = concat!(
    "\n\n# Prelude reference (authoritative — generated from source)\n\n",
    include_str!(concat!(env!("OUT_DIR"), "/prelude_signatures.txt")),
);

#[derive(Parser, Debug)]
#[command(about = "Exarch — a delegate driving ral under a grant", long_about = None)]
pub struct Cli {
    /// All flags are long-form only — short-letter aliases collide
    /// with each other in unhelpful ways (e.g. `-p` provider vs
    /// prompt) and there are few enough flags that long names are
    /// fine.
    #[arg(long, value_enum, default_value_t = ProviderKind::Anthropic)]
    pub provider: ProviderKind,
    #[arg(long)]
    pub model: Option<String>,
    #[arg(long, conflicts_with = "file")]
    pub prompt: Option<String>,
    #[arg(long)]
    pub file: Option<std::path::PathBuf>,
    #[arg(long = "system", value_name = "FILE")]
    pub system_files: Vec<std::path::PathBuf>,
}

/// Resolve `--system FILE...` into the narrative half of the prompt
/// (default = baked `data/` markdown), then unconditionally append the
/// generated prelude reference.  The reference is non-overridable on
/// purpose — if the user's narrative claims something exists that
/// doesn't, the listing below tells the truth.
pub fn load_system(files: &[std::path::PathBuf]) -> Result<String, String> {
    let narrative = if files.is_empty() {
        NARRATIVE.into()
    } else {
        let mut buf = String::new();
        for path in files {
            if !buf.is_empty() {
                buf.push_str("\n\n");
            }
            buf.push_str(
                &std::fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))?,
            );
        }
        buf
    };
    Ok(format!("{narrative}{PRELUDE_REF}"))
}

/// Resolve `-p/-f` into an optional initial prompt.
pub fn load_seed(prompt: Option<String>, file: Option<std::path::PathBuf>) -> Result<Option<String>, String> {
    Ok(match (prompt, file) {
        (Some(p), _) => Some(p),
        (_, Some(path)) => {
            Some(std::fs::read_to_string(&path).map_err(|e| format!("{}: {e}", path.display()))?)
        }
        _ => None,
    })
}
