//! Assemble the system prompt from its parts.
//!
//! Each entry is a `(heading, body)` pair; one renderer walks them
//! uniformly so the shape of the prompt is the shape of the Vec built
//! in `assemble`.  Headed sections get a `# heading` line; the persona
//! section is unheaded — it sets the tone, not a topic.

use crate::host;
use ral_core::types::{Capabilities, ExecPolicy};
use std::path::{Path, PathBuf};

/// Generated by `build.rs` from the same schemes the exarch runs
/// with.  Non-overridable on purpose: if a custom narrative claims a
/// builtin exists that doesn't, this listing tells the truth.
const PRELUDE_BODY: &str = include_str!(concat!(env!("OUT_DIR"), "/prelude_signatures.txt"));

/// Build the full system prompt.  With no `--system` files the
/// bake-in persona (`data/system.md`) and ral guide (`data/ral.md`)
/// appear as two distinct sections; `--system FILE...` collapses both
/// into one user-supplied section.  Host, grant, and prelude are
/// always appended.
pub fn assemble(files: &[PathBuf], caps: &Capabilities, scratch: &Path) -> Result<String, String> {
    let mut sections: Vec<(Option<&str>, String)> = Vec::new();
    if files.is_empty() {
        sections.push((None,        include_str!("../data/system.md").into()));
        sections.push((Some("Ral"), include_str!("../data/ral.md").into()));
    } else {
        sections.push((None, read_files(files)?));
    }
    sections.push((Some("Host"),                                       host::snapshot()));
    sections.push((Some("Grant"),                                      grant_summary(caps, scratch)));
    sections.push((Some("Prelude reference (authoritative)"),          PRELUDE_BODY.into()));
    Ok(render(&sections))
}

/// Concatenate `--system` files with blank-line separators, in the
/// order given on the command line.
fn read_files(files: &[PathBuf]) -> Result<String, String> {
    let mut buf = String::new();
    for path in files {
        if !buf.is_empty() {
            buf.push_str("\n\n");
        }
        buf.push_str(&std::fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))?);
    }
    Ok(buf)
}

/// Render the section list.  Headed sections get a `# heading` line;
/// unheaded sections are emitted verbatim.  Bodies are trimmed and
/// joined by a blank line.
fn render(sections: &[(Option<&str>, String)]) -> String {
    sections.iter().map(|(h, body)| match h {
        None    => body.trim_end().to_string(),
        Some(h) => format!("# {h}\n\n{}", body.trim_end()),
    }).collect::<Vec<_>>().join("\n\n") + "\n"
}

/// Render the live grant as a bullet list.  `None` fields are
/// "unrestricted" (no attenuation at this layer); empty containers
/// are "(none)".  One effect per line so the agent can scan its
/// authority at a glance and avoid burning turns on denied ops.
fn grant_summary(caps: &Capabilities, scratch: &Path) -> String {
    let mut s = String::new();
    s.push_str(&format!("- exec: {}\n", exec_line(caps)));
    let denies = exec_denies(caps);
    if !denies.is_empty() {
        s.push_str(&format!("- exec deny: {}\n", denies.join(", ")));
    }
    if let Some(dirs) = &caps.exec_dirs {
        s.push_str(&format!("- exec dirs: {}\n", or_none(dirs)));
    }
    if let Some(fs) = &caps.fs {
        s.push_str(&format!("- fs read: {}\n",  or_none(&fs.read_prefixes)));
        s.push_str(&format!("- fs write: {}\n", or_none(&fs.write_prefixes)));
        if !fs.deny_paths.is_empty() {
            s.push_str(&format!("- fs deny: {}\n", fs.deny_paths.join(", ")));
        }
    }
    s.push_str(&format!("- net: {}\n", match caps.net {
        None        => "inherit",
        Some(true)  => "allow",
        Some(false) => "deny",
    }));
    s.push_str(&format!("- scratch: `$EXARCH_SCRATCH` = {}\n", scratch.display()));
    s
}

/// Per-command exec policy as `name` or `name[sub1,sub2,...]`,
/// comma-joined.  `None` (no exec map) is "unrestricted"; empty map
/// (or one with only `Deny` entries) is "(none)".  `Deny` entries
/// are surfaced separately by [`exec_denies`].
fn exec_line(caps: &Capabilities) -> String {
    let Some(m) = &caps.exec else { return "unrestricted".into() };
    let admitted: Vec<String> = m.iter().filter_map(|(name, pol)| match pol {
        ExecPolicy::Allow             => Some(name.clone()),
        ExecPolicy::Subcommands(subs) => Some(format!("{name}[{}]", subs.join(","))),
        ExecPolicy::Deny              => None,
    }).collect();
    if admitted.is_empty() { "(none)".into() } else { admitted.join(", ") }
}

/// Names with an explicit `Deny` policy — vetoed even if `exec_dirs`
/// would admit their resolved path.
fn exec_denies(caps: &Capabilities) -> Vec<String> {
    caps.exec.as_ref().map_or_else(Vec::new, |m| {
        m.iter()
            .filter_map(|(name, pol)| matches!(pol, ExecPolicy::Deny).then(|| name.clone()))
            .collect()
    })
}

fn or_none(v: &[String]) -> String {
    if v.is_empty() { "(none)".into() } else { v.join(", ") }
}
